---
# ansible-playbook deploy_elasticsearch.yml -vv --private-key=/path/to/ec2/pri/key

---
- name: Stage instance(s)
  hosts: localhost
  connection: local
  user: root
  gather_facts: false
  tags:
    - stage

tasks:
  - name: Launch the new EC2 Instance
    ec2:
      instance_type: t2.micro
      group: manish-SG
      count: 3
      key_name: awskeypair
      image: ami-0fc20dd1da406jkhy
      region: us-east-2
      vpc_subnet_id: subnet-0b67481hg7v82fc2d5a
      wait: yes
      assign_public_ip: yes
    register: ec2

  - name: Add the newly created host so that we can further contact it
      add_host:
        name: "{{ item.public_ip }}"
        groups: deploy
      with_items: "{{ ec2.instances }}"


- name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"

- name: accept new ssh fingerprints
    shell: ssh-keyscan -H {{ item.public_ip }} >> ~/.ssh/known_hosts
    with_items: '{{ ec2.instances }}'

- name: Breathing room (Ansible uses python apt, has issues running directly after boot)
    pause: seconds=15

- name: Configuring ElasticSearch
  hosts: deploy
  user: ubuntu
  become_method: sudo
  become: true
  gather_facts: false

tags:
  - config
  - configure

tasks:
  - name: update cache and ignore errors in case of problems
  become: yes
  apt: update_cache=yes
  ignore_errors: yes

  - name: install nginx
      become: yes
      apt:
        name: nginx
        purge: yes
        state: present

  - name: install java 11
      become: yes
      apt:
        name: openjdk-11-jdk
        purge: yes
        state: present

  - name: Set Java home
      shell: sudo echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> /etc/environment

      - name: export Java home
          shell: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

  - name: Download ElasticSearch package
      shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

  - name: check package list
      shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

  - name: update cache and ignore errors in case of problems
      become: yes
      apt: update_cache=yes
      ignore_errors: yes

  - name: install elasticsearch
      become: yes
      apt:
        name: elasticsearch
        purge: yes
        state: present
      notify: restart elasticsearch

  - name:  over Elasticsearch settings
      copy: src=./elasticsearch/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

  - name: Copy over nginx default file
      copy: src=./elasticsearch/default dest=/etc/nginx/sites-available/default
      notify: restart nginx

  - name: Copy over chain file
      copy: src=./elasticsearch/fullchain.pem dest=/etc/nginx/sites-available/fullchain.pem
      notify: restart nginx

      - name: Copy over pvt keypair
          copy: src=./elasticsearch/privkey.pem dest=/etc/nginx/sites-available/privkey.pem
          notify: restart nginx

  handlers:
    - name: restart elasticsearch
      action: service name=elasticsearch state=restarted

    - name: restart nginx
        action: service name=nginx state=restartedCopy